version: "3.7"

services:
  tb-mqtt-transport:
    image: thingsboard/tb-mqtt-transport:2.5.0
    container_name: "tb-mqtt-transport"
    ports:
      - "1883:1883" 
    env_file:
      - "./tb-mqtt-transport.env"         
    volumes: 
      - "./conf:/config"
    networks:
      - "tb-net"
    depends_on:
      - "kafka"           

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    environment:
      - "ZOO_ENABLE_AUTH=yes"
      - "ZOO_SERVER_USERS=kafka"
      - "ZOO_SERVER_PASSWORDS=kafka_password"
    networks:
      - "tb-net"

  kafka:
    image: "bitnami/kafka:latest"
    container_name: "kafka"
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - "KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "ALLOW_PLAINTEXT_LISTENER=yes"
      - "KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      - "KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      - "KAFKA_ZOOKEEPER_USER=kafka"
      - "KAFKA_ZOOKEEPER_PASSWORD=kafka_password"
    networks:
      - "tb-net"
    depends_on:
      - "zookeeper" 

networks:
  tb-net:
    external: false
    name: "tb-net"      
